"use client";
// Lightweight i18n: English, Indonesian (Indonesia), and Chinese (中国人) support.
import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "en" | "id" | "zh";

export interface Translation {
  // Header / nav
  live: string;
  searchPlaceholder: string;
  watchlist: string;
  toggleTheme: string;
  markets: string;
  assetsCount: (n: number) => string;
  backToDashboard: string;

  // Tabs
  tabAll: string;
  tabStocks: string;
  tabCrypto: string;
  tabGainers: string;
  tabLosers: string;

  // Table headers
  colAsset: string;
  colPrice: string;
  colChange: string;
  colMarketCap: string;
  colVolume: string;
  colTrend: string;
  addWatch: string;
  removeWatch: string;
  noResults: string;

  // Index labels
  ixSp500: string;
  ixNasdaq: string;
  ixDow: string;

  // Asset types
  typeCrypto: string;
  typeStock: string;
  assetTypeCrypto: string;
  assetTypeStock: string;
  rank: (n: number | string) => string;
  equity: string;

  // Stats
  high24: string;
  low24: string;

  // Chart
  aiForecast: string;
  aiTarget: string;

  // Indicators
  techIndicators: string;
  rsiSignal: string;
  bullish: string;
  bearish: string;
  neutral: string;
  overbought: string;
  oversold: string;
  macdBullish: string;
  macdBearish: string;
  bollinger: string;
  upperBand: string;
  middleBand: string;
  lowerBand: string;

  // Predictions
  aiPredictions: string;
  hour1: string;
  hour1Sub: string;
  hour24: string;
  hour24Sub: string;
  day7: string;
  day7Sub: string;
  confidence: string;
  predictionUnavailable: string;
  runningModel: string;
  support: string;
  resistance: string;

  // Watchlist page
  myWatchlist: string;
  watchCount: (n: number) => string;
  addAssets: string;
  emptyTitle: string;
  emptyBody: string;
  browseMarkets: string;
  remove: string;
  tracked: string;

  // Asset detail
  watch: string;
  watched: string;
  today: string;
  assetNotFound: string;

  // Footer
  footer: string;
  footerDetail: string;

  // Prediction rationale heuristics
  rationaleUp: string;
  rationaleDown: string;
  rationaleFlat: string;

  // News
  newsTitle: string;
  newsCrypto: string;
  newsStocks: string;
  newsAll: string;
  newsRefresh: string;
  newsEmpty: string;
  newsUpdated: string;
  newsReadMore: string;
}

const en: Translation = {
  live: "LIVE",
  searchPlaceholder: "Search stocks & crypto (BTC, AAPL…)",
  watchlist: "Watchlist",
  toggleTheme: "Toggle theme",
  markets: "Markets",
  assetsCount: (n) => `${n} assets · auto-refresh 8s`,
  backToDashboard: "Dashboard",

  tabAll: "All",
  tabStocks: "Stocks",
  tabCrypto: "Crypto",
  tabGainers: "Top Gainers",
  tabLosers: "Top Losers",

  colAsset: "Asset",
  colPrice: "Price",
  colChange: "24h %",
  colMarketCap: "Market Cap",
  colVolume: "Volume (24h)",
  colTrend: "7d Trend",
  addWatch: "Add to watchlist",
  removeWatch: "Remove from watchlist",
  noResults: "No assets match your search.",

  ixSp500: "S&P 500",
  ixNasdaq: "Nasdaq 100",
  ixDow: "Dow Jones",

  typeCrypto: "Crypto",
  typeStock: "Stock",
  assetTypeCrypto: "Cryptocurrency",
  assetTypeStock: "Equity",
  rank: (n) => `Rank #${n}`,
  equity: "Equity",

  high24: "24h High",
  low24: "24h Low",

  aiForecast: "AI forecast",
  aiTarget: "AI Target",

  techIndicators: "Technical Indicators",
  rsiSignal: "RSI (14)",
  bullish: "Bullish",
  bearish: "Bearish",
  neutral: "Neutral",
  overbought: "Overbought",
  oversold: "Oversold",
  macdBullish: "MACD Bullish",
  macdBearish: "MACD Bearish",
  bollinger: "Bollinger Bands (20, 2σ)",
  upperBand: "Upper",
  middleBand: "Middle (SMA)",
  lowerBand: "Lower",

  aiPredictions: "AI Price Predictions",
  hour1: "1 Hour",
  hour1Sub: "short-term momentum",
  hour24: "24 Hours",
  hour24Sub: "intraday swing",
  day7: "7 Days",
  day7Sub: "weekly trend",
  confidence: "confidence",
  predictionUnavailable: "Prediction engine unavailable right now.",
  runningModel: "Running AI model…",
  support: "Support (24h)",
  resistance: "Resistance (24h)",

  myWatchlist: "My Watchlist",
  watchCount: (n) => `${n} tracked asset${n === 1 ? "" : "s"} · saved locally`,
  addAssets: "+ Add assets",
  emptyTitle: "Your watchlist is empty",
  emptyBody: "Tap the star on any asset to track it here.",
  browseMarkets: "Browse markets",
  remove: "Remove",
  tracked: "tracked asset",

  watch: "Watch",
  watched: "Watched",
  today: "today",
  assetNotFound: "Asset not found",

  footer:
    "Real-time data from CoinGecko & market feeds. Predictions are AI-generated and for educational purposes only — not financial advice.",
  footerDetail:
    "Data refreshes every 8 seconds. AI predictions are generated by a machine-learning model and are for educational purposes only — not financial advice.",

  rationaleUp:
    "SMA-20 above SMA-50 indicates an established uptrend; momentum favours continued drift higher with pullback risk toward the moving average.",
  rationaleDown:
    "SMA-20 below SMA-50 signals downtrend pressure; price remains capped by near-term resistance with support at recent swing lows.",
  rationaleFlat:
    "Price is consolidating near its moving averages with balanced momentum; expect range-bound behaviour until a breakout confirms direction.",

  newsTitle: "Market News",
  newsCrypto: "Crypto",
  newsStocks: "Stocks",
  newsAll: "All",
  newsRefresh: "Refresh",
  newsEmpty: "No news available right now.",
  newsUpdated: "Updated",
  newsReadMore: "Read more",
};

const id: Translation = {
  ...en,
  live: "LANGSUNG",
  searchPlaceholder: "Cari saham & kripto (BTC, AAPL…)",
  watchlist: "Daftar Pantauan",
  toggleTheme: "Ganti tema",
  markets: "Pasar",
  assetsCount: (n) => `${n} aset · segarkan otomatis 8dtk`,
  backToDashboard: "Dasbor",

  tabAll: "Semua",
  tabStocks: "Saham",
  tabCrypto: "Kripto",
  tabGainers: "Pemenang Teratas",
  tabLosers: "Pecundang Teratas",

  colAsset: "Aset",
  colPrice: "Harga",
  colChange: "24 jam %",
  colMarketCap: "Kapitalisasi",
  colVolume: "Volume (24 jam)",
  colTrend: "Tren 7 hari",
  addWatch: "Tambah ke daftar pantauan",
  removeWatch: "Hapus dari daftar pantauan",
  noResults: "Tidak ada aset yang cocok dengan pencarian Anda.",

  ixSp500: "S&P 500",
  ixNasdaq: "Nasdaq 100",
  ixDow: "Dow Jones",

  typeCrypto: "Kripto",
  typeStock: "Saham",
  assetTypeCrypto: "Mata Uang Kripto",
  assetTypeStock: "Efek",
  rank: (n) => `Peringkat #${n}`,
  equity: "Efek",

  high24: "Tertinggi 24 jam",
  low24: "Terendah 24 jam",

  aiForecast: "Perkiraan AI",
  aiTarget: "Target AI",

  techIndicators: "Indikator Teknis",
  rsiSignal: "RSI (14)",
  bullish: "Bullish",
  bearish: "Bearish",
  neutral: "Netral",
  overbought: "Overbought",
  oversold: "Oversold",
  macdBullish: "MACD Bullish",
  macdBearish: "MACD Bearish",
  bollinger: "Bollinger Bands (20, 2σ)",
  upperBand: "Atas",
  middleBand: "Tengah (SMA)",
  lowerBand: "Bawah",

  aiPredictions: "Prediksi Harga AI",
  hour1: "1 Jam",
  hour1Sub: "momentum jangka pendek",
  hour24: "24 Jam",
  hour24Sub: "pergerakan intraday",
  day7: "7 Hari",
  day7Sub: "tren mingguan",
  confidence: "keyakinan",
  predictionUnavailable: "Mesin prediksi tidak tersedia saat ini.",
  runningModel: "Menjalankan model AI…",
  support: "Dukungan (24 jam)",
  resistance: "Resistensi (24 jam)",

  myWatchlist: "Daftar Pantauan Saya",
  watchCount: (n) => `${n} aset yang dipantau · disimpan lokal`,
  addAssets: "+ Tambah aset",
  emptyTitle: "Daftar pantauan Anda kosong",
  emptyBody: "Ketuk bintang pada aset mana pun untuk melacaknya di sini.",
  browseMarkets: "Jelajahi pasar",
  remove: "Hapus",
  tracked: "aset yang dipantau",

  watch: "Pantau",
  watched: "Dipantau",
  today: "hari ini",
  assetNotFound: "Aset tidak ditemukan",

  footer:
    "Data waktu nyata dari CoinGecko & umpan pasar. Prediksi dihasilkan AI dan hanya untuk tujuan edukasi — bukan nasihat keuangan.",
  footerDetail:
    "Data diperbarui setiap 8 detik. Prediksi AI dihasilkan oleh model pembelajaran mesin dan hanya untuk tujuan edukasi — bukan nasihat keuangan.",

  rationaleUp:
    "SMA-20 di atas SMA-50 menunjukkan tren naik yang mapan; momentum mendukung kenaikan lanjutan dengan risiko koreksi menuju rata-rata bergerak.",
  rationaleDown:
    "SMA-20 di bawah SMA-50 menandakan tekanan tren turun; harga dibatasi resistensi jangka pendek dengan dukungan di level terendah baru.",
  rationaleFlat:
    "Harga mengonsolidasi dekat rata-rata bergeraknya dengan momentum seimbang; perkirakan pergerakan terbatas hingga penembusan mengonfirmasi arah.",

  newsTitle: "Berita Pasar",
  newsCrypto: "Kripto",
  newsStocks: "Saham",
  newsAll: "Semua",
  newsRefresh: "Segarkan",
  newsEmpty: "Tidak ada berita saat ini.",
  newsUpdated: "Diperbarui",
  newsReadMore: "Baca selengkapnya",
};

const zh: Translation = {
  ...en,
  live: "实时",
  searchPlaceholder: "搜索股票与加密货币 (BTC、AAPL…)",
  watchlist: "自选列表",
  toggleTheme: "切换主题",
  markets: "市场",
  assetsCount: (n) => `${n} 个资产 · 每 8 秒自动刷新`,
  backToDashboard: "仪表盘",

  tabAll: "全部",
  tabStocks: "股票",
  tabCrypto: "加密货币",
  tabGainers: "涨幅领先",
  tabLosers: "跌幅领先",

  colAsset: "资产",
  colPrice: "价格",
  colChange: "24小时 %",
  colMarketCap: "市值",
  colVolume: "成交量 (24小时)",
  colTrend: "7天趋势",
  addWatch: "加入自选",
  removeWatch: "移出自选",
  noResults: "没有符合您搜索的资产。",

  ixSp500: "标普500",
  ixNasdaq: "纳斯达克100",
  ixDow: "道琼斯",

  typeCrypto: "加密货币",
  typeStock: "股票",
  assetTypeCrypto: "加密货币",
  assetTypeStock: "证券",
  rank: (n) => `排名 #${n}`,
  equity: "证券",

  high24: "24小时最高",
  low24: "24小时最低",

  aiForecast: "AI 预测",
  aiTarget: "AI 目标",

  techIndicators: "技术指标",
  rsiSignal: "RSI (14)",
  bullish: "看涨",
  bearish: "看跌",
  neutral: "中性",
  overbought: "超买",
  oversold: "超卖",
  macdBullish: "MACD 看涨",
  macdBearish: "MACD 看跌",
  bollinger: "布林带 (20, 2σ)",
  upperBand: "上轨",
  middleBand: "中轨 (SMA)",
  lowerBand: "下轨",

  aiPredictions: "AI 价格预测",
  hour1: "1 小时",
  hour1Sub: "短期动量",
  hour24: "24 小时",
  hour24Sub: "日内波动",
  day7: "7 天",
  day7Sub: "周趋势",
  confidence: "置信度",
  predictionUnavailable: "预测引擎当前不可用。",
  runningModel: "正在运行 AI 模型…",
  support: "支撑位 (24小时)",
  resistance: "阻力位 (24小时)",

  myWatchlist: "我的自选",
  watchCount: (n) => `已关注 ${n} 个资产 · 保存在本地`,
  addAssets: "+ 添加资产",
  emptyTitle: "您的自选列表是空的",
  emptyBody: "点击任意资产上的星标即可在此跟踪。",
  browseMarkets: "浏览市场",
  remove: "移除",
  tracked: "已关注资产",

  watch: "关注",
  watched: "已关注",
  today: "今日",
  assetNotFound: "未找到资产",

  footer:
    "实时数据来自 CoinGecko 与市场数据源。预测由 AI 生成，仅供教育用途——不构成财务建议。",
  footerDetail:
    "数据每 8 秒刷新。AI 预测由机器学习模型生成，仅供教育用途——不构成财务建议。",

  rationaleUp:
    "SMA-20 高于 SMA-50 表明上升趋势确立；动量支持继续走高，但存在回撤至均线的风险。",
  rationaleDown:
    "SMA-20 低于 SMA-50 表明下行压力；价格受近期阻力压制，支撑位位于近期低点。",
  rationaleFlat:
    "价格在均线附近盘整，动量均衡；预计区间震荡，直至突破确认方向。",

  newsTitle: "市场新闻",
  newsCrypto: "加密货币",
  newsStocks: "股票",
  newsAll: "全部",
  newsRefresh: "刷新",
  newsEmpty: "当前暂无新闻。",
  newsUpdated: "更新时间",
  newsReadMore: "阅读更多",
};

const translations: Record<Lang, Translation> = { en, id, zh };

const LangCtx = createContext<{
  lang: Lang;
  t: Translation;
  setLang: (l: Lang) => void;
}>({ lang: "en", t: en, setLang: () => {} });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("pm-lang") as Lang | null;
    if (saved && translations[saved]) setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    try {
      localStorage.setItem("pm-lang", l);
    } catch {
      /* ignore */
    }
  };

  return (
    <LangCtx.Provider value={{ lang, t: translations[lang], setLang }}>
      {children}
    </LangCtx.Provider>
  );
}

export const useLang = () => useContext(LangCtx);

// Translate a heuristic rationale into the active language.
export function translateRationale(enText: string, t: Translation): string {
  if (!enText) return "";
  const lower = enText.toLowerCase();
  if (lower.includes("established uptrend") || lower.includes("momentum favours")) return t.rationaleUp;
  if (lower.includes("downtrend pressure") || lower.includes("signals downtrend")) return t.rationaleDown;
  if (lower.includes("consolidating") || lower.includes("range-bound")) return t.rationaleFlat;
  return enText;
}
